In [1]:
import numpy as np
import scipy as sp
import scipy.linalg as linalg
from scipy.optimize import minimize_scalar

In [2]:
matrix = np.array([[1,-1,-1],[-1,1,-1], [-1,-1,1]])
# 行列式
print(linalg.det(matrix))

-4.0


In [3]:
print('逆行列', linalg.inv(matrix))
print('単位行列', matrix.dot(linalg.inv(matrix)))

逆行列 [[ 0.  -0.5 -0.5]
 [-0.5 -0.  -0.5]
 [-0.5 -0.5  0. ]]
単位行列 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**3つの固有値と固有ベクトルが見つかった**

In [6]:
eig_value, eig_vector = linalg.eig(matrix)
print('固有値', eig_value) 
print('固有ベクトル', eig_vector) 

固有値 [-1.+0.j  2.+0.j  2.+0.j]
固有ベクトル [[ 0.57735027  0.81649658  0.40824829]
 [ 0.57735027 -0.40824829 -0.81649658]
 [ 0.57735027 -0.40824829  0.40824829]]


In [8]:
def my_fuction(x):
    return (x**2 + 2*x + 1)

In [10]:
from scipy.optimize import newton
print(newton(my_fuction, 0))

-0.9999999852953906


In [12]:
print(minimize_scalar(my_fuction, method='Brent'))

 message: 
          Optimization terminated successfully;
          The returned value satisfies the termination criteria
          (using xtol = 1.48e-08 )
 success: True
     fun: 0.0
       x: -1.0000000000000002
     nit: 4
    nfev: 8


**練習問題**

In [14]:
matrix = np.array([[1,2,3], [1,3,2], [3,1,2]])
print(linalg.det(matrix))

-12.0


In [23]:
inv = linalg.inv(matrix)
eig_value, eig_vector = linalg.eig(matrix)
print('逆行列', inv)
print('固有値', eig_value)
print('固有ベクトル', eig_vector)

逆行列 [[-0.33333333  0.08333333  0.41666667]
 [-0.33333333  0.58333333 -0.08333333]
 [ 0.66666667 -0.41666667 -0.08333333]]
固有値 [ 6.        +0.j -1.41421356+0.j  1.41421356+0.j]
固有ベクトル [[-0.57735027 -0.72236645  0.16041816]
 [-0.57735027 -0.14290228 -0.81090869]
 [-0.57735027  0.67658381  0.56275492]]


In [26]:
def sample_function(x):
    return (x**3 + 2*x + 1)

In [28]:
print(newton(sample_function, 0))

-0.45339765151640365
