In [2]:
import numpy as np
import scipy as sp
import scipy.linalg as linalg
from scipy.optimize import minimize_scalar

In [3]:
matrix = np.array([[1,-1,-1],[-1,1,-1], [-1,-1,1]])
# 行列式
print(linalg.det(matrix))

-4.0


In [7]:
print('逆行列', linalg.inv(matrix))
print('単位行列', matrix.dot(linalg.inv(matrix)))

逆行列 [[ 0.  -0.5 -0.5]
 [-0.5 -0.  -0.5]
 [-0.5 -0.5  0. ]]
単位行列 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
