In [1]:
import numpy as np

In [2]:
%precision 3

'%.3f'

## 配列操作

In [23]:
data = np.array([9,2,3,4,10,6,7,8,1,5])

In [4]:
data

array([ 9,  2,  3,  4, 10,  6,  7,  8,  1,  5])

In [5]:
data.dtype

dtype('int64')

In [6]:
print('次元数', data.ndim)
print('要素数', data.size)

次元数 1
要素数 10


In [24]:
data

array([ 9,  2,  3,  4, 10,  6,  7,  8,  1,  5])

**sortは破壊的メソッド**

In [35]:
data.sort()

**numpyにはcopyとviewの概念があり、スライスは新しいviewを作る**
sort()メソッドをviewに適用すると、そのビューを通じて参照されている元の配列のデータが変更される。
スライスによる逆順のビューでsort()を呼び出すと、元のデータが逆順で昇順にソートされるため、結果として元の配列が降順でソートされた状態になる。
- copy
 - 元の配列と違うメモリを使用しているが要素が同一の意味を持つもの
- view
 - 元の配列と同じメモリを参照しているもの

https://deepage.net/features/numpy-copyview.html

In [27]:
data[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [33]:
data[::-1].sort()

In [34]:
data

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

## 乱数
seedとは乱数を作るための基となるデータであり、特に指定しない場合はシステム時刻が採用される。
そのため、同じ乱数が作られることはほとんどない。
逆にseed値を指定すると同じ乱数が作られる

In [5]:
import numpy.random as random 
random.seed(0)
rnd_data = random.random(10)

print("乱数10個の配列", rnd_data)

乱数10個の配列 [0.549 0.715 0.603 0.545 0.424 0.646 0.438 0.892 0.964 0.383]


In [46]:
random.seed(0)
rnd_data = random.random(10)

print("乱数10個の配列", rnd_data)

乱数10個の配列 [0.549 0.715 0.603 0.545 0.424 0.646 0.438 0.892 0.964 0.383]


In [4]:
data = np.array([1,2,3,4])

**復元抽出 replace=True**
  - ランダムで値を抽出する際に、重複を許可する

**非復元抽出 replace=False**
  - ランダムで値を抽出する際に、重複を許可する

In [10]:
print('復元抽出', random.choice(data,4))
print('非復元抽出', random.choice(data,4, replace=False))

復元抽出 [1 2 2 2]
非復元抽出 [3 4 1 2]


## 行列

In [22]:
array1 = np.arange(9).reshape(3,3)
print(array1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


**行列の各要素へのアクセス**

In [24]:
# data[行,列]でアクセスする
print('1行目全部', array1[0, :])
print('1行目2列目', array1[0, 1])
print('3列目全部', array1[:, 2])

1行目全部 [0 1 2]
1行目2列目 1
3列目全部 [2 5 8]


In [26]:
array2 = np.arange(9,18).reshape(3,3)
print(array2)

[[ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [30]:
# 行列の積の計算
print(np.dot(array1, array2))

# 要素の積の計算になってしまうため、注意
print(array1 * array2)

[[ 42  45  48]
 [150 162 174]
 [258 279 300]]
[[  0  10  22]
 [ 36  52  70]
 [ 90 112 136]]


In [37]:
print(np.zeros((2, 3), dtype=np.int64))
print(np.ones((2, 3)))

[[0 0 0]
 [0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]]


## 練習問題

In [12]:
np.array([i for i in range(1, 51)]).sum()

1275

In [14]:
import numpy.random as random 
random.seed(0)
rnd_data = random.randn(10)

print("最大値", rnd_data.max())
print("最小値", rnd_data.min())
print("最小値", rnd_data.sum())

最大値 2.240893199201458
最小値 -0.977277879876411
最小値 7.380231707288347


In [16]:
matrix = np.ones((5, 5)) * 3 
matrix.dot(matrix)

array([[45., 45., 45., 45., 45.],
       [45., 45., 45., 45., 45.],
       [45., 45., 45., 45., 45.],
       [45., 45., 45., 45., 45.],
       [45., 45., 45., 45., 45.]])